   var $css = $("<link/>"); 
                $css.attr("href", "http://local.support.cz/stylesheets/css/bootstrap-prefixed.css");
                $css.attr("rel", "stylesheet");
                $("head").append($css); 
                if(!(typeof $().emulateTransitionEnd == "function")) { 
                    var js = document.createElement("script"); 
                    js.src = "//netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js";
                    js.type = "text/javascript";
                    document.getElementsByTagName("body")[0].appendChild(js); 
            }
            $("body").append('<div id="support-button" class="bootstrap-styles" style="position: fixed;right: 0px;bottom: 100px"><a data-toggle="modal" href="#sp-modal"  class="btn btn-primary btn-lg">Contact Us</a></div>');$("body").append('<div class="bootstrap-styles"><div id="sp-modal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true" class="modal fade"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h4 class="modal-title">What do you need?</h4></div><div class="modal-body"><form role="form" action="http://local.support.cz/submit.php" id="sp-support-forms"><input id="domain" name="domain" type="hidden"><div id="alertMessage" class="alert" style="display:none;"></div><input type="hidden" name="formId" value="6"><input type="hidden" name="userId" value="1"><div class="form-group"><label for="name">Meno</label><input name="name" type="text" placeholder="Your name" id="name" class="form-control" required="required"></div><div class="form-group"><label for="surname">Priezvisko</label><input name="surname" type="text" placeholder="Your surname" id="surname" class="form-control" required="required"></div><div class="form-group"><label for="number">Telefón</label><input name="number" type="text" placeholder="Your phone no." id="number" class="form-control"></div><div class="form-group"><label for="email">Email</label><input name="email" type="email" placeholder="Your email" id="email" class="form-control"></div><div class="form-group"><label for="mess">Správa</label><textarea name="mess" type="textarea" placeholder="Your message" id="mess" class="form-control"></textarea></div><div class="btn-group btn-group-justified"><a href="skype:adams" type="skype" class="btn-primary btn">Skype: test</a><a onclick="$(function(){ $(&quot;#submitNewForm&quot;).trigger(&quot;click&quot;); });" type="submit" class="btn-danger btn">odoslat</a><input type="submit" id="submitNewForm" style="display: none;"></div></form></div></div></div></div></div>');$("#domain").val(window.location.hostname);$('form#sp-support-forms').on('submit', function(e) { e.preventDefault();var parsed=null; $.post($(this).attr('action'), $(this).serializeArray(), function(data) { $('#alertMessage').addClass(data['class']); $('#alertMessage').show(); $('#alertMessage').html(data['alertMessage']);},'json'); });